layout_spectrum: 0.9111326029524207
typography_spectrum: 0.635021586669609
color:
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
  brandStrength: 0.47673931531608105
  lightness: 0.6228584703058004
  saturation: 0.08980355993844569
  rhythmicContrast: 0.22883410076610744
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Ben Finley
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ben Finley
description: ''
purpose: []
