typography_spectrum: 0.6006057332269847
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9792066900990903
  lightness: 0.18217399856075644
  saturation: 0.6038182249758393
  rhythmicContrast: 0.6640453562140465
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5075736260041595
analytics:
  google: null
  facebook: null
  twitter: null
name: Ben Finley
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Ben Finley
purpose: []
